# Generated by Django 6.0.2 on 2026-04-01 15:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.CharField(max_length=50)),
                ('zone_nom', models.CharField(max_length=100)),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('heure_debut', models.CharField(default='08:00', max_length=5)),
                ('heure_fin', models.CharField(default='18:00', max_length=5)),
                ('acces_autorise', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'access_rules',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=200)),
                ('type_notification', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=10)),
                ('categorie', models.CharField(choices=[('confirmation', 'Confirmation'), ('rappel', 'Rappel'), ('annulation', 'Annulation'), ('alerte', 'Alerte'), ('maintenance', 'Maintenance')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(default='envoyee', max_length=20)),
                ('reservation_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_id', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('bureau_id', models.CharField(blank=True, max_length=50)),
                ('employe_id', models.CharField(max_length=50)),
                ('employe_nom', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nb_participants', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('en_attente', 'En attente'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='confirmee', max_length=20)),
                ('recurrence', models.CharField(blank=True, max_length=20)),
                ('recurrence_end', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('salle', 'Salle'), ('materiel', 'Matériel'), ('equipement', 'Équipement'), ('vehicule', 'Véhicule'), ('laboratoire', 'Laboratoire'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.TextField(blank=True)),
                ('caracteristiques', models.JSONField(default=dict)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('bureau_associe', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('maintenance', 'En maintenance'), ('reserve', 'Réservé'), ('hors_service', 'Hors service')], default='disponible', max_length=50)),
                ('capacite', models.IntegerField(default=1)),
                ('disponibilite_heures', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('badge_rfid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='utilisateur_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilisateur_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
