# Generated by Django 6.0.2 on 2026-04-08 14:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('salle', 'Salle'), ('materiel', 'Matériel'), ('equipement', 'Équipement'), ('vehicule', 'Véhicule'), ('laboratoire', 'Laboratoire'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.TextField(blank=True)),
                ('caracteristiques', models.JSONField(default=dict)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('bureau_associe', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('maintenance', 'En maintenance'), ('reserve', 'Réservé'), ('hors_service', 'Hors service')], default='disponible', max_length=50)),
                ('capacite', models.IntegerField(default=1)),
                ('disponibilite_heures', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'db_table': 'resources',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('badge_rfid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='utilisateur_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilisateur_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.CharField(max_length=50)),
                ('zone_nom', models.CharField(max_length=100)),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('heure_debut', models.CharField(default='08:00', max_length=5)),
                ('heure_fin', models.CharField(default='18:00', max_length=5)),
                ('acces_autorise', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Règle d'accès",
                'verbose_name_plural': "Règles d'accès",
                'db_table': 'access_rules',
                'unique_together': {('employe_id', 'zone_nom', 'jour', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.TextField(blank=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant IA'), ('system', 'Système')], max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('entities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.chatbotconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_id', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('bureau_id', models.CharField(blank=True, max_length=50)),
                ('employe_id', models.CharField(max_length=50)),
                ('employe_nom', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nb_participants', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('en_attente', 'En attente'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='confirmee', max_length=20)),
                ('recurrence', models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='none', max_length=20)),
                ('recurrence_end', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['resource_id', 'statut'], name='reservation_resourc_e91114_idx'), models.Index(fields=['employe_id', 'date_debut'], name='reservation_employe_33ee7a_idx'), models.Index(fields=['date_debut', 'date_fin'], name='reservation_date_de_b57392_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('system', 'Système')], default='system', max_length=20)),
                ('categorie', models.CharField(choices=[('reservation', 'Réservation'), ('rappel', 'Rappel'), ('alerte', 'Alerte'), ('info', 'Information'), ('confirmation', 'Confirmation'), ('annulation', 'Annulation')], default='info', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='🔔', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('archive', 'Archivé')], default='non_lu', max_length=20)),
                ('reservation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_django',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_c1b90f_idx'), models.Index(fields=['-created_at'], name='notificatio_created_7c2979_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('timeout', 'Expiration'), ('terminated', 'Terminée par admin')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique session',
                'verbose_name_plural': 'Historique des sessions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='dashboard_s_user_id_b95a2c_idx'), models.Index(fields=['action', 'timestamp'], name='dashboard_s_action_376594_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Ordinateur'), ('mobile', 'Mobile'), ('tablet', 'Tablette'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['session_key'], name='dashboard_u_session_2a760d_idx'), models.Index(fields=['user', 'is_active'], name='dashboard_u_user_id_85ba93_idx'), models.Index(fields=['is_active', 'last_activity'], name='dashboard_u_is_acti_de236a_idx')],
            },
        ),
    ]
