# Generated by Django 4.1.13 on 2026-04-21 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adminnotification_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotconversation',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatbotconversation',
            name='context',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
