# Generated by Django 6.0.2 on 2026-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_utilisateur_options_usersession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Session utilisateur', 'verbose_name_plural': 'Sessions utilisateurs'},
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='dashboard_u_session_2a760d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='dashboard_u_user_id_85ba93_idx'),
        ),
    ]
