# Generated by Django 4.1.13 on 2026-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_chatbotconversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='state',
            field=models.JSONField(default=dict),
        ),
    ]
