# Generated by Django 6.0.2 on 2026-04-04 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_usersession_options_usersession_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.TextField(blank=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('timeout', 'Expiration'), ('terminated', 'Terminée par admin')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Historique session',
                'verbose_name_plural': 'Historique des sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
                'db_table': 'system_config',
            },
        ),
        migrations.AlterModelOptions(
            name='accessrule',
            options={'verbose_name': "Règle d'accès", 'verbose_name_plural': "Règles d'accès"},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('confirmation', 'Confirmation'), ('rappel', 'Rappel'), ('annulation', 'Annulation'), ('alerte', 'Alerte'), ('maintenance', 'Maintenance'), ('info', 'Information')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('envoyee', 'Envoyée'), ('echouee', 'Échouée'), ('en_attente', 'En attente')], default='envoyee', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook'), ('push', 'Push')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Ordinateur'), ('mobile', 'Mobile'), ('tablet', 'Tablette'), ('unknown', 'Inconnu')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='accessrule',
            unique_together={('employe_id', 'zone_nom', 'jour', 'mois', 'annee')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['resource_id', 'statut'], name='reservation_resourc_e91114_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['employe_id', 'date_debut'], name='reservation_employe_33ee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date_debut', 'date_fin'], name='reservation_date_de_b57392_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', 'last_activity'], name='dashboard_u_is_acti_de236a_idx'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['user', 'timestamp'], name='dashboard_s_user_id_b95a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['action', 'timestamp'], name='dashboard_s_action_376594_idx'),
        ),
    ]
