# Generated by Django 4.1.13 on 2026-05-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_chatbotmessage_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=100)),
                ('reservation_titre', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('approbateur_id', models.CharField(max_length=100)),
                ('approbateur_nom', models.CharField(blank=True, max_length=200)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegant_id', models.CharField(max_length=100)),
                ('delegant_nom', models.CharField(max_length=200)),
                ('delegataire_id', models.CharField(max_length=100)),
                ('delegataire_nom', models.CharField(max_length=200)),
                ('delegataire_email', models.CharField(blank=True, max_length=200)),
                ('motif', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reservation_id', models.CharField(max_length=100)),
                ('demandeur_id', models.CharField(max_length=100)),
                ('demandeur_nom', models.CharField(max_length=200)),
                ('approbateur_id', models.CharField(max_length=100)),
                ('ressource_nom', models.CharField(max_length=200)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nb_participants', models.IntegerField(default=1)),
                ('niveau', models.IntegerField(default=1)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('role_concerne', models.CharField(blank=True, help_text="ex: 'directeur', 'chef_zone', 'employe'", max_length=50)),
                ('categorie_ressource', models.CharField(blank=True, help_text="ex: 'salle', 'vehicule' — vide = toutes", max_length=50)),
                ('duree_max_minutes', models.IntegerField(default=0, help_text='0 = illimité. Auto-approuve si durée <= cette valeur')),
                ('nb_participants_max', models.IntegerField(default=0, help_text='0 = illimité')),
                ('auto_approve', models.BooleanField(default=False)),
                ('niveau_approbation_requis', models.IntegerField(default=1, help_text='1 = responsable zone, 2 = + direction')),
                ('actif', models.BooleanField(default=True)),
                ('priorite', models.IntegerField(default=100, help_text='Plus petit = évalué en premier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_rules',
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_nom', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=100)),
                ('user_nom', models.CharField(max_length=200)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('date_debut_souhaitee', models.DateTimeField()),
                ('date_fin_souhaitee', models.DateTimeField()),
                ('nb_participants', models.IntegerField(default=1)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(help_text='ID du bureau ou zone', max_length=100)),
                ('zone_nom', models.CharField(max_length=200)),
                ('manager_id', models.CharField(max_length=100)),
                ('manager_nom', models.CharField(max_length=200)),
                ('manager_email', models.EmailField(max_length=254)),
                ('niveau', models.IntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zone_managers',
                'unique_together': {('zone_id', 'manager_id', 'niveau')},
            },
        ),
    ]
